version: "3.9"

services:
  # Create service with RabbitMQ.
  rabbitmq:
    image: sactio1811/rabbitmq-delay-arm64
    ports:
      - "5672:5672" # for sender and consumer connections
      - "15672:15672" # for serve RabbitMQ GUI
    restart: always
    networks:
      - kb-backend

  vaccination-api:
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    command: ["/bin/bash", "-c", "./api"]
    restart: always
    networks:
      - kb-backend


  vaccination-register:
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: [ "/bin/bash", "-c", "./consumer_registration" ]
    restart: always
    networks:
      - kb-backend

#  vaccination-vaccine:
#    depends_on:
#      - rabbitmq
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
#    command: [ "/bin/bash", "-c", "./consumer_vaccination" ]
#    restart: always
#    networks:
#      - kb-backend

networks:
  kb-backend:
    driver: bridge
    external: false
    name: kb-backend