version: "3.9"

services:
  # Create service with RabbitMQ.
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: message-broker
    ports:
      - 5672:5672 # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq
      - ./rabbitmq/log/:/var/log/rabbitmq
    restart: always

  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    restart: always
    volumes:
      - "./docker/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - 5432:5432

  vaccination-api:
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["/bin/bash", "-c", "./api"]
    restart: always